### ISSUE TITLE
Looking for paper : Higher-Order Reactive Programming with Incremental 

### ISSUE THREAD

**Issue by hhugo** [ingoem/scala-react#6]
Sorry to post this here, I couldn't reach you with your email @epfl.ch

I'm working on FRP programming with incremental data structure update
(see https://github.com/hhugo/reactiveData)

Your paper, "Higher-Order Reactive Programming with Incremental
Lists", seems to be close to what I'm doing.
I was wondering if you could provide me with a copy of this paper. I would
love to read it.

**Comment by glenviewjeff** [comment]
I guess that's a no! :)
